// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | DarkCarrouselSlice
  | EditorialImageBlockSlice
  | HeroVideoSlice
  | VideoBlockSlice
  | EditorialSectionSlice
  | TestimonialSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *DarkCarrousel → Default → Primary → Features*
 */
export interface DarkCarrouselSliceDefaultPrimaryFeaturesItem {
  /**
   * Image field in *DarkCarrousel → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dark_carrousel.default.primary.features[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *DarkCarrousel → Default → Primary*
 */
export interface DarkCarrouselSliceDefaultPrimary {
  /**
   * Top Title  field in *DarkCarrousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Top Title
   * - **API ID Path**: dark_carrousel.default.primary.top_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_title: prismic.KeyTextField;

  /**
   * Title field in *DarkCarrousel → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: dark_carrousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *DarkCarrousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text
   * - **API ID Path**: dark_carrousel.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Features field in *DarkCarrousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: dark_carrousel.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<DarkCarrouselSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for DarkCarrousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DarkCarrouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DarkCarrouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DarkCarrousel*
 */
type DarkCarrouselSliceVariation = DarkCarrouselSliceDefault;

/**
 * DarkCarrousel Shared Slice
 *
 * - **API ID**: `dark_carrousel`
 * - **Description**: DarkCarrousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DarkCarrouselSlice = prismic.SharedSlice<
  "dark_carrousel",
  DarkCarrouselSliceVariation
>;

/**
 * Primary content in *EditorialImageBlock → Default → Primary*
 */
export interface EditorialImageBlockSliceDefaultPrimary {
  /**
   * Top Title  field in *EditorialImageBlock → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Top Title
   * - **API ID Path**: editorial_image_block.default.primary.top_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_title: prismic.TitleField;

  /**
   * Title field in *EditorialImageBlock → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: editorial_image_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *EditorialImageBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text
   * - **API ID Path**: editorial_image_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * CTA field in *EditorialImageBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CTA
   * - **API ID Path**: editorial_image_block.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta: prismic.RichTextField;
}

/**
 * Default variation for EditorialImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorialImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EditorialImageBlock*
 */
type EditorialImageBlockSliceVariation = EditorialImageBlockSliceDefault;

/**
 * EditorialImageBlock Shared Slice
 *
 * - **API ID**: `editorial_image_block`
 * - **Description**: EditorialImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorialImageBlockSlice = prismic.SharedSlice<
  "editorial_image_block",
  EditorialImageBlockSliceVariation
>;

/**
 * Primary content in *EditorialSection → Default → Primary*
 */
export interface EditorialSectionSliceDefaultPrimary {
  /**
   * Top Title  field in *EditorialSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Top Title
   * - **API ID Path**: editorial_section.default.primary.top_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_title: prismic.TitleField;

  /**
   * Title field in *EditorialSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: editorial_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *EditorialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text
   * - **API ID Path**: editorial_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for EditorialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EditorialSection*
 */
type EditorialSectionSliceVariation = EditorialSectionSliceDefault;

/**
 * EditorialSection Shared Slice
 *
 * - **API ID**: `editorial_section`
 * - **Description**: EditorialSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorialSectionSlice = prismic.SharedSlice<
  "editorial_section",
  EditorialSectionSliceVariation
>;

/**
 * Primary content in *HeroVideo → Default → Primary*
 */
export interface HeroVideoSliceDefaultPrimary {
  /**
   * Logo field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: hero_video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Video Background field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Video Background
   * - **API ID Path**: hero_video.default.primary.video_background
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_background: prismic.EmbedField;
}

/**
 * Default variation for HeroVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroVideo*
 */
type HeroVideoSliceVariation = HeroVideoSliceDefault;

/**
 * HeroVideo Shared Slice
 *
 * - **API ID**: `hero_video`
 * - **Description**: HeroVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSlice = prismic.SharedSlice<
  "hero_video",
  HeroVideoSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Quote field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Quote
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Video link field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Video link
   * - **API ID Path**: video_block.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_link: prismic.EmbedField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      DarkCarrouselSlice,
      DarkCarrouselSliceDefaultPrimaryFeaturesItem,
      DarkCarrouselSliceDefaultPrimary,
      DarkCarrouselSliceVariation,
      DarkCarrouselSliceDefault,
      EditorialImageBlockSlice,
      EditorialImageBlockSliceDefaultPrimary,
      EditorialImageBlockSliceVariation,
      EditorialImageBlockSliceDefault,
      EditorialSectionSlice,
      EditorialSectionSliceDefaultPrimary,
      EditorialSectionSliceVariation,
      EditorialSectionSliceDefault,
      HeroVideoSlice,
      HeroVideoSliceDefaultPrimary,
      HeroVideoSliceVariation,
      HeroVideoSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
