// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  dark_carrousel: dynamic(() => import("./DarkCarrousel")),
  editorial_image_block: dynamic(() => import("./EditorialImageBlock")),
  editorial_section: dynamic(() => import("./EditorialSection")),
  hero_video: dynamic(() => import("./HeroVideo")),
  rich_text: dynamic(() => import("./RichText")),
  testimonial: dynamic(() => import("./Testimonial")),
  video_block: dynamic(() => import("./VideoBlock")),
};
